complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
filesize_format = "B"
filesize_metric = true
nonzero_exit_errors = true
pivot_mode = "auto"
plugin_dirs = ["D:\\Src\\GitHub\\nu-plugin-lib\\samples\\Nu.Plugin.Len\\bin\\Debug\\netcoreapp3.1"]
prompt = "echo (starship prompt)"
rm_always_trash = true
skip_welcome_message = false
startup = ["alias la = ls --long", "def nudown [] {fetch https://api.github.com/repos/nushell/nushell/releases | get assets | select name download_count}", "def nuver [] {version | pivot key value}"]
table_mode = "other"

[color_config]
header_align = "l"
header_bold = true
header_color = "c"
index_color = "rd"
leading_trailing_space_bg = "white"
primitive_binary = "cyan"
primitive_boolean = "green"
primitive_columnpath = "cyan"
primitive_date = "ru"
primitive_decimal = "red"
primitive_duration = "blue"
primitive_filesize = "ur"
primitive_int = "green"
primitive_line = "yellow"
primitive_path = "yellow"
primitive_pattern = "white"
primitive_range = "purple"
primitive_string = "pb"
separator_color = "purple"

[line_editor]
auto_add_history = true
bell_style = "audible"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "circular"
edit_mode = "emacs"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"

[env]
STARSHIP_SHELL = "nushell"
